#!/bin/bash

# these commands load the proper env for snakemake and the pipeline
module purge
. /etc/profile.d/modules.sh
module load modules modules-init modules-gs/prod modules-eichler
module load anaconda/20161130
base2="/net/eichler/vol2/home/mvollger/projects/cmpSeq/"
snake="cmpSeq.py"
NPROC=$(nproc)

# sometimes snakemake fails in a really bad way and it leaves to lock on the dir
# this is probably bad practive but oh well
if [ "unlock" == "unlock" ]; then
    snakemake --unlock -s $base2/$snake
fi

n=$(nproc)
snakemake -j $n --rerun-incomplete -p --cores $NPROC -s $base2/$snake


